### PR TITLE
Add superProperties on initialize

### PR DESCRIPTION
**Pull request by gabrielferreir**
Hi, I'm adding the properties parameter to the init method.

https://github.com/mixpanel/mixpanel-android/issues/597

### CODE REVIEW

**Comment by toshiossada** [comment]
When this will accepted?

**Comment by henriquemello** [comment]
Please, could you guys check this solution?

**Review by zihejia — APPROVED** [review]
Thank you so much @gabrielferreir !

**Comment by zihejia** [comment]
sorry guys for the waiting. I will do a release for the PR!

**Pull request merged**
